const images = [

    {id: 1, src: 'files/characters/bot-1.svg', title: 'Bot', description: 'Super Bot'},
    {id: 2, src: 'files/characters/bull-1.svg', title: 'Bull', description: 'Super Bull'},
    {id: 3, src: 'files/characters/cat-1.png', title: 'Cat', description: 'Super Cat'},
    {id: 4, src: 'files/characters/cat-2.png', title: 'Cat', description: 'Super Cat'},
    {id: 5, src: 'files/characters/cat-2.png', title: 'Cat', description: 'Super Cat'},
    {id: 6, src: 'files/characters/crow-1.png', title: 'Crow', description: 'Super Crow'},
    {id: 7, src: 'files/characters/crow-2.png', title: 'Crow', description: 'Super Crow'},
    {id: 8, src: 'files/characters/crow-3.png', title: 'Crow', description: 'Super Crow'},
    {id: 9, src: 'files/characters/crow-4.png', title: 'Crow', description: 'Super Crow'},
    {id: 10, src: 'files/characters/crow-5.png', title: 'Crow', description: 'Super Crow'},
    {id: 11, src: 'files/characters/dog-1.svg', title: 'Dog', description: 'Super Dog'},
    {id: 12, src: 'files/characters/dog-2.svg', title: 'Dog', description: 'Super Dog'},
    {id: 13, src: 'files/characters/dog-3.svg', title: 'Dog', description: 'Super Dog'},
    {id: 14, src: 'files/characters/dog-4.svg', title: 'Dog', description: 'Super Dog'},
    {id: 15, src: 'files/characters/dog-5.svg', title: 'Dog', description: 'Super Dog'},
    {id: 16, src: 'files/characters/dog-6.svg', title: 'Dog', description: 'Super Dog'},
    {id: 17, src: 'files/characters/mare-1.svg', title: 'Mare', description: 'Super Mare'},
    {id: 18, src: 'files/characters/mare-2.svg', title: 'Mare', description: 'Super Mare'},
    {id: 19, src: 'files/characters/mare-3.svg', title: 'Mare', description: 'Super Mare'},
    {id: 20, src: 'files/characters/mare-4.svg', title: 'Mare', description: 'Super Mare'},

    {id: 22, src: 'files/characters/mare-6.svg', title: 'Mare', description: 'Super Mare'},
    {id: 23, src: 'files/characters/mare-7.svg', title: 'Mare', description: 'Super Mare'},
    {id: 24, src: 'files/characters/mare-8.svg', title: 'Mare', description: 'Super Mare'},
    {id: 25, src: 'files/characters/mare-9.svg', title: 'Mare', description: 'Super Mare'},
    {id: 26, src: 'files/characters/pig-1.svg', title: 'Pig', description: 'Super Pig'},
    {id: 27, src: 'files/characters/pig-2.svg', title: 'Pig', description: 'Super Pig'},
    {id: 28, src: 'files/characters/pig-3.svg', title: 'Pig', description: 'Super Pig'},
    {id: 29, src: 'files/characters/pig-4.svg', title: 'Pig', description: 'Super Pig'},
    {id: 30, src: 'files/characters/pig-5.svg', title: 'Pig', description: 'Super Pig'},
    {id: 31, src: 'files/characters/rabbit-1.svg', title: 'Rabbit', description: 'Super Rabbit'},
    {id: 32, src: 'files/characters/sheep-1.svg', title: 'Sheep', description: 'Super Sheep'},
    {id: 33, src: 'files/characters/sheep-2.svg', title: 'Sheep', description: 'Super Sheep'},
    {id: 34, src: 'files/characters/sheep-3.svg', title: 'Sheep', description: 'Super Sheep'},
    {id: 35, src: 'files/characters/sheep-4.svg', title: 'Sheep', description: 'Super Sheep'},
    {id: 36, src: 'files/characters/sheep-5.svg', title: 'Sheep', description: 'Super Sheep'},
]

export default images